window.WORK_STUDIES = {
  courseId: 'years-11-12-work-studies',
  storageKey: 'wwhs-work-studies-stage6-v1',
  title: 'Years 11–12 Work Studies',
  subtitle: 'Stage 6 Content Endorsed Course',
  status: 'Provisional two-year pathway · check your teacher’s current instructions',
  modules: [
    {id:'C00',slug:'core-my-working-life',number:'C',year:'Year 11',hours:30,title:'Core: My Working Life',summary:'Understand changing work, make informed pathway decisions and build a sustainable working life.',sections:[['C00-S01','Work in contemporary Australia'],['C00-S02','Self-knowledge, pathways and career decisions'],['C00-S03','Managing change and building a sustainable working life']]},
    {id:'M01',slug:'in-the-workplace',number:'01',year:'Year 11',hours:15,title:'In the Workplace',summary:'Read workplace structures, participate safely and understand culture, performance and change.',sections:[['M01-S01','Workplace structures, roles and relationships'],['M01-S02','Rights, responsibilities and safe participation'],['M01-S03','Workplace culture, performance and change']]},
    {id:'M02',slug:'preparing-job-applications',number:'02',year:'Year 11',hours:15,title:'Preparing Job Applications',summary:'Interpret opportunities, present evidence and prepare for interviews with purpose.',sections:[['M02-S01','Reading opportunities and selection criteria'],['M02-S02','Building evidence-based applications'],['M02-S03','Interview preparation, performance and reflection']]},
    {id:'M03',slug:'workplace-communication',number:'03',year:'Year 11',hours:15,title:'Workplace Communication',summary:'Choose suitable channels, communicate professionally and repair misunderstandings.',sections:[['M03-S01','Purpose, audience and communication channels'],['M03-S02','Professional spoken, written and digital communication'],['M03-S03','Feedback, conflict and communication repair']]},
    {id:'M04',slug:'teamwork-enterprise-skills',number:'04',year:'Year 11',hours:30,title:'Teamwork and Enterprise Skills',summary:'Build trust, solve problems and apply initiative to authentic work.',sections:[['M04-S01','Team roles, trust and shared goals'],['M04-S02','Initiative, problem-solving and decision-making'],['M04-S03','Enterprise skills in authentic work']]},
    {id:'M09',slug:'team-enterprise-project',number:'09',year:'Year 11',hours:15,title:'Team Enterprise Project',summary:'Plan, deliver and evaluate a purposeful team enterprise.',sections:[['M09-S01','Defining the problem and project purpose'],['M09-S02','Planning roles, resources, risks and communication'],['M09-S03','Delivering, evaluating and presenting enterprise evidence']]},
    {id:'M05',slug:'managing-work-life',number:'05',year:'Year 12',hours:30,title:'Managing Work and Life Commitments',summary:'Set realistic priorities, protect wellbeing and adapt plans when life changes.',sections:[['M05-S01','Time, priorities and realistic boundaries'],['M05-S02','Wellbeing, stress and support'],['M05-S03','Adapting plans across changing life stages']]},
    {id:'M06',slug:'personal-finance',number:'06',year:'Year 12',hours:30,title:'Personal Finance',summary:'Understand pay, manage money and make safer long-term financial decisions.',sections:[['M06-S01','Pay, tax, superannuation and records'],['M06-S02','Budgeting, banking, credit and saving'],['M06-S03','Consumer decisions, risk and future planning']]},
    {id:'M07',slug:'workplace-issues',number:'07',year:'Year 12',hours:30,title:'Workplace Issues',summary:'Investigate workplace issues, weigh perspectives and choose evidence-based responses.',sections:[['M07-S01','Recognising contemporary workplace issues'],['M07-S02','Analysing impacts, evidence and perspectives'],['M07-S03','Responding through policy, support and action']]},
    {id:'M08',slug:'self-employment',number:'08',year:'Year 12',hours:15,title:'Self-Employment',summary:'Test a useful idea, understand obligations and plan a small enterprise.',sections:[['M08-S01','From strengths and needs to a viable idea'],['M08-S02','Business models, obligations and risk'],['M08-S03','Planning, communicating and reviewing a micro-enterprise']]},
    {id:'M10',slug:'experiencing-work',number:'10',year:'Year 12',hours:15,title:'Experiencing Work',summary:'Prepare, participate, record evidence and transfer workplace learning.',sections:[['M10-S01','Preparing for workplace experience'],['M10-S02','Observing, participating and recording evidence'],['M10-S03','Reflecting, transferring learning and planning next steps']]}
  ]
};
